parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
plugins:
  - standard
  - promise
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
env:
  browser: true
  node: true
  es6: true
  jest: true
rules:
  no-console: 0
